### ISSUE TITLE
Feature Request: Support wildcards in module matches

### ISSUE THREAD

**Issue by XLTechie** [accessolutions/WebAccessForNVDA#23]
I think it would be most helpful, if the URLs which modules match against, could support wildcards.

They may already, as I suspect regular expressions may be used here, but if so that doesn't seem to be documented. Even if they do already in regular expression format, I think the simplified Windows style would probably be more friendly to most users.

For example, I wished to create a module which allowed navigating by issue title, on GitHub issue search pages.
To do this, it would be nice if the module would only work on pages with a URL of:

```
https://github.com/*/issues?q=
```

Or even, if necessary:

```
https://github.com/*/*/issues?q=
```

Note, in this case, the question mark is actually part of the URL, not intended as part of the wildcard. However even if it was, in the traditional meaning of "match one character" (and not the regular expression meaning), it would still match the question mark that is part of the query string.

As it stands, the first URL above causes a module not to match, on a GitHub issues page.

**Comment by AAClause** [comment]
Hello,

Thank you for your suggestion and interest.

The standard approach is to design a specific webmodule for each site, followed by the creation of contextual rules (Page Type, Page Title, Parent Element, global).

In your case, you could create a webmodule that triggers in the case where the URL contains github.com and then set up two rules like this:

1. A "Page Type" rule, designed to detect pages that list "Issues".
2. A marker-type rule to navigate by issue title, configured as follow:

	- To apply only to pages with the given type (i.e. the context defined by the previously rule);
	- To support "Multiple Results".

Here is a corresponding JSON

<details>
<summary>Show/hide</summary>

```
{
    "WebModule": {
        "name": "github",
        "url": [
            "github.com"
        ],
        "windowTitle": "",
        "help": ""
    },
    "formatVersion": "0.7-dev",
    "Rules": {
        "Issues list": {
            "name": "Issues list",
            "type": "pageType",
            "criteria": [
                {
                    "text": "Issues list",
                    "tag": "h2",
                    "className": "new-discussion-timeline"
                }
            ],
            "gestures": {},
            "multiple": false,
            "formMode": false,
            "skip": false,
            "sayName": true
        },
        "issue": {
            "name": "issue",
            "type": "marker",
            "criteria": [
                {
                    "contextPageType": "Issues list",
                    "tag": "a",
                    "id": "issue_*",
                    "className": "markdown-title"
                }
            ],
            "gestures": {},
            "multiple": true,
            "formMode": false,
            "skip": false,
            "sayName": true
        }
    }
}
```

</details>

To try this, copy this content into a file named "github.json", then save this file in the "webModulesMC" directory located at the root of the NVDA user folder. After that, you can use page up/page down to navigate between issue titles.

Hope that helps,

**Comment by XLTechie** [comment]
Thank you @aaclause, I will certainly try this!
I was not aware that rules could be chained like that.
