### ISSUE TITLE
Bug in script_sayall

### ISSUE THREAD

**Issue by javidominguez** [accessolutions/WebAccessForNVDA#28]
The "Say all" action doesn't work because this error occurs:  

> Error in func SingleNodeResult.script_sayall
> Traceback (most recent call last):
>   File "queueHandler.pyc", line 64, in flushQueue
>   File "C:\Users\JaviD\AppData\Roaming\nvda\addons\webAccess\globalPlugins\webAccess\ruleHandler\__init__.py", line 983, in script_sayall
>     speechMode = speech.speechMode
> AttributeError: module 'speech' has no attribute 'speechMode'

I think speechMode is with the S in capital letters.  

> \>\>\> speech.SpeechMode
> <enum 'SpeechMode'>  

I am using version 2024.03.11 of the addon. The error occurs in all versions of NVDA, 2023.3.4, 2024.1RC1 and alpha-31515,38efb1cf (2024.2.0.31515).

**Comment by AAClause** [comment]
Thanks for the report. Should be fixed by #29, updated script:

```python
	def script_sayall(self, gesture, fromQuickNav=False):
		speech.cancelSpeech()
		if self.rule.sayName:
			speech.speakMessage(self.label)
		treeInterceptor = html.getTreeInterceptor()
		if not treeInterceptor:
			return
		speechMode = speech.getState().speechMode
		try:
			speech.speechMode = speech.SpeechMode.off
			treeInterceptor.passThrough = False
			browseMode.reportPassThrough.last = treeInterceptor.passThrough
			self.node.moveto()
			html.speakLine()
			api.processPendingEvents()
		except Exception:
			log.exception("Error during script_sayall")
			return
		finally:
			speech.setSpeechMode(speechMode)
		speech.sayAll.SayAllHandler.readText(
			speech.sayAll.CURSOR.CARET
		)
```
